apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-events-app
spec:
  selector:
    matchLabels:
      app: rails-events-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rails-events-app
        version: original
    spec:
      containers:
        - name: rails-events-app
          image: basilmawejje/rails-events:v1
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: rails-events-config
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-events-app-canary-test
spec:
  selector:
    matchLabels:
      app: rails-events-app
  replicas: 1
  template:
    metadata:
      labels:
        app: rails-events-app
        version: experimental
    spec:
      containers:
        - name: rails-events-app
          image: basilmawejje/rails-events:v1
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 500Mi
              cpu: 200m
          envFrom:
            - configMapRef:
                name: rails-events-config
          imagePullPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-events-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
     app: rails-events-frontend
  template:
    metadata:
      labels:
        app: rails-events-frontend
        version: frontend
    spec:
      containers:
      - name: react-kubernetes-app
        image: basilmawejje/rails-events-frontend:latest
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rails-events-app
spec:
  selector:
    app: rails-events-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
 name: rails-events-frontend
spec:
  type: NodePort
  selector:
    app: rails-events-frontend
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31010
