version: '2'

services:
  postgres:
    image: 'postgres:10.3-alpine'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'
    ports:
      - '5432:5432'

  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'
    ports:
      - '6379:6379'

  website:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/rails-events
    env_file:
      - '.env'
    environment:
      DATABASE_URL: postgres://postgres@postgres
      REDIS_URL: redis://redis:6379/0

  sidekiq:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: sidekiq
    volumes:
      - '.:/app'
    environment:
      REDIS_URL: redis://redis:6379/0

volumes:
  redis:
  postgres: