apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres
    spec:
      containers:
        - env:
            - name: COMPOSE_PROJECT_NAME
              value: rails-events
            - name: DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL
              value: "true"
            - name: PUBLISHABLE_KEY
              value: pk_test_Okp6mq2W0Ttopccq3HFOy5zC
            - name: SECRET_KEY
              value: sk_test_30kbW7W8ql8cfpVseTZYcSPq
            - name: gmail_password
              value: goodasfidem26
            - name: gmail_username
              value: basil.mawejje@gmail.com
          image: postgres:10.3-alpine
          name: postgres
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      restartPolicy: Always
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres
status: {}
