branch-defaults:
  master:
    environment: $CIRCLE_BRANCH-rails-events
global:
  application_name: Rails Events
  default_ec2_keyname: 
  default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
  default_region: eu-west-1
  sc: git