jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install-deps
  checking:
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - ruby/install-deps
  test:
    docker:
      - image: 'cimg/ruby:2.7-node'
      - image: 'circleci/redis:latest'
      - environment:
          POSTGRES_DB: rails-events_test
          POSTGRES_PASSWORD: ''
          POSTGRES_USER: postgres
        image: 'circleci/postgres:9.5-alpine'
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      PGHOST: 127.0.0.1
      PGPASSWORD: ''
      PGUSER: postgres
      RAILS_ENV: test
    parallelism: 3
    steps:
      - checkout
      - ruby/install-deps
      - run:
          command: 'dockerize -wait tcp://localhost:5432 -timeout 1m'
          name: Wait for DB
      - run:
          command: 'bundle exec rails db:schema:load --trace'
          name: Database setup
      - run:
          name: Run tests
          command: |
            bundle exec rspec --profile 10 \
                              --format progress
  deploy:
    working_directory: ~/app
    docker:
      - image: 'cimg/ruby:2.7-node'
    steps:
      - checkout
      - run:
          name: Installing deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: Deploying to EBS
          command: eb deploy $CIRCLE_BRANCH-rails-events
orbs:
  node: circleci/node@4.6.0
  ruby: circleci/ruby@1.1.4
version: 2.1
workflows:
  build_and_test:
    jobs:
      - build
      - checking
      - test:
          requires:
            - build
  deploy_to_EBS:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - staging
                - master