default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails-events_development

test:
  <<: *default
  database: rails-events_test
  host: localhost

production:
  <<: *default
  database: rails-events_production
  username: rails-events
  password: <%= ENV['RAILS-EVENTS_DATABASE_PASSWORD'] %>