default: &default
  adapter: postgresql
  encoding: unicode
  host: 127.0.0.1
  username: root
  password:
  pool: 5

development:
  <<: *default
  database: rails-events_development

test:
  <<: *default
  database: rails-events_test