default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: rails-events_development

test:
  <<: *default
  database: rails-events_test