default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  host: postgres
  port: 5432

development:
  <<: *default
  database: rails-events_development

test:
  <<: *default
  database: rails-events_test

production:
  <<: *default
  database: rails-events_production
  username: rails-events
  password: <%= ENV['RAILS-EVENTS_DATABASE_PASSWORD'] %>
