apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ingress-gateway-configuration
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "railsevents.local"
    - "developer.railsevents.local"
    - "frontend.railsevents.local"
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: rails-events-app-virtual-service
  namespace: default
spec:
  hosts:
    - "railsevents.local"
  gateways:
    - ingress-gateway-configuration
  http:
    - route:
        - destination:
            host: rails-events-app
            subset: original
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: rails-events-app-canary-test-virtual-service
  namespace: default
spec:
  hosts:
    - "developer.railsevents.local"
  gateways:
    - ingress-gateway-configuration
  http:
      - route:
        - destination:
            host: rails-events-app
            subset: experimental
---
kind: VirtualService
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: rails-events-frontend-virtual-service
  namespace: default
spec:
  hosts:
    - "frontend.railsevents.local"
  gateways:
    - ingress-gateway-configuration
  http:
      - route:
        - destination:
            host: rails-events-frontend
            subset: frontend
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: rails-events-app-destination-rule
  namespace: default
spec:
  host: rails-events-app
  subsets:
    - labels:
        version: original
      name: original
    - labels:
        version: experimental
      name: experimental
  trafficPolicy:
    outlierDetection:
      maxEjectionPercent: 100
---
kind: DestinationRule
apiVersion: networking.istio.io/v1alpha3
metadata:
  name: rails-events-frontend-destination-rule
  namespace: default
spec:
  host: rails-events-frontend
  subsets:
    - labels:
        version: frontend
      name: frontend
  trafficPolicy:
    outlierDetection:
      maxEjectionPercent: 100
